adb shell
pm disable --user 0 com.samsung.aasaservice
pm disable --user 0 com.sec.hearingadjust
pm disable --user 0 com.google.android.ext.services
pm disable --user 0 com.sec.android.preloadinstaller
pm disable --user 0 com.samsung.android.ardrawing
pm disable --user 0 com.samsung.android.aremoji
pm disable --user 0 com.samsung.android.aremojieditor
pm disable --user 0 com.samsung.android.arzone
pm disable --user 0 com.samsung.android.tapack.authfw
pm disable --user 0 com.sec.android.autodoodle.service
pm disable --user 0 com.samsung.android.samsungpassautofill
pm disable --user 0 com.sec.android.app.DataCreate
pm disable --user 0 com.sec.android.provider.badge
pm disable --user 0 com.samsung.android.bbc.bbcagent
pm disable --user 0 com.samsung.android.visionintelligence
pm disable --user 0 com.samsung.android.bixbyvision.framework
pm disable --user 0 com.samsung.android.bluelightfilter
pm disable --user 0 com.sec.android.app.bluetoothtest
pm disable --user 0 com.samsung.android.mdecservice
pm disable --user 0 com.sec.factory.cameralyzer
pm disable --user 0 com.samsung.android.cidmanager
pm disable --user 0 com.samsung.cmh
pm disable --user 0 com.mediatek
pm disable --user 0 com.mediatek.systemuiresoverlay
pm disable --user 0 com.samsung.android.accessibility.talkback
pm disable --user 0 com.samsung.android.appseparation
pm disable --user 0 com.samsung.android.callbgprovider
pm disable --user 0 com.samsung.android.cmfa.framework
pm disable --user 0 com.samsung.android.hdmapp
pm disable --user 0 com.samsung.android.knox.attestation
pm disable --user 0 com.samsung.android.knox.pushmanager
pm disable --user 0 com.samsung.android.localeoverlaymanager
pm disable --user 0 com.samsung.android.mapsagent
pm disable --user 0 com.samsung.android.mcfds
pm disable --user 0 com.samsung.android.mcfserver
pm disable --user 0 com.samsung.android.networkdiagnostic
pm disable --user 0 com.samsung.android.networkstack
pm disable --user 0 com.samsung.android.networkstack.tethering.overlay
pm disable --user 0 com.samsung.android.privateshare
pm disable --user 0 com.samsung.android.scs
pm disable --user 0 com.samsung.android.server.wifi.mobilewips
pm disable --user 0 com.samsung.android.service.stplatform
pm disable --user 0 com.samsung.android.smartsuggestions
pm disable --user 0 com.samsung.android.smartswitchassistant
pm disable --user 0 com.samsung.android.wifi.resources
pm disable --user 0 com.samsung.android.wifi.softap.resources
pm disable --user 0 com.samsung.memorysaver
pm disable --user 0 com.sec.android.app.chromecustomizations
pm disable --user 0 com.sec.bcservice
pm disable --user 0 com.sec.enterprise.knox.attestation
pm disable --user 0 com.sec.epdg
pm disable --user 0 com.wssyncmldm
pm disable --user 0 com.samsung.android.app.omcagent
pm disable --user 0 com.samsung.android.providers.carrier
pm disable --user 0 com.samsung.android.sdm.config
pm disable --user 0 com.samsung.android.container
pm disable --user 0 com.samsung.sec.android.application.csc
pm disable --user 0 com.samsung.android.rubin.app
pm disable --user 0 com.samsung.android.livestickers
pm disable --user 0 com.samsung.android.sm.devicesecurity
pm disable --user 0 com.sec.android.app.factorykeystring
pm disable --user 0 com.sec.factory
pm disable --user 0 com.sec.android.diagmonagent
pm disable --user 0 com.samsung.android.forest
pm disable --user 0 com.samsung.android.dqagent
pm disable --user 0 com.sec.android.app.parser
pm disable --user 0 com.samsung.android.dsms
pm disable --user 0 com.samsung.android.da.daagent
pm disable --user 0 com.sec.android.emergencymode.service
pm disable --user 0 com.sec.android.provider.emergencymode
pm disable --user 0 com.sec.enterprise.mdm.services.simpin
pm disable --user 0 com.sec.epdgtestapp
pm disable --user 0 com.facebook.system
pm disable --user 0 com.samsung.faceservice
pm disable --user 0 com.samsung.android.aircommandmanager
pm disable --user 0 com.sec.factory.camera
pm disable --user 0 com.samsung.android.fmm
pm disable --user 0 com.samsung.android.app.galaxyfinder
pm disable --user 0 com.sec.android.app.samsungapps
pm disable --user 0 com.samsung.android.themestore
pm disable --user 0 com.samsung.android.themecenter
pm disable --user 0 com.samsung.storyservice
pm disable --user 0 com.samsung.android.sdk.handwriting
pm disable --user 0 com.sec.android.app.hwmoduletest
pm disable --user 0 com.sec.imsservice
pm disable --user 0 com.samsung.advp.imssettings
pm disable --user 0 com.sec.imslogger
pm disable --user 0 com.samsung.ipservice
pm disable --user 0 com.samsung.android.icecone
pm disable --user 0 com.samsung.klmsagent
pm disable --user 0 com.samsung.android.knox.analytics.uploader
pm disable --user 0 com.sec.enterprise.knox.cloudmdm.smdms
pm disable --user 0 com.samsung.knox.keychain
pm disable --user 0 com.knox.vpn.proxyhandler
pm disable --user 0 com.samsung.android.app.simplesharing
pm disable --user 0 com.samsung.android.mdx
pm disable --user 0 com.samsung.android.mdx.kit
pm disable --user 0 com.samsung.android.mdm
pm disable --user 0 com.samsung.android.mdx.quickboard
pm disable --user 0 com.samsung.android.easysetup
pm disable --user 0 com.samsung.android.allshare.service.mediashare
pm disable --user 0 com.netflix.mediaclient
pm disable --user 0 com.sec.vsim.ericssonnsds.webapp
pm disable --user 0 com.samsung.android.service.peoplestripe
pm disable --user 0 com.sec.android.app.personalization
pm disable --user 0 com.samsung.android.knox.containercore
pm disable --user 0 com.samsung.android.app.sharelive
pm disable --user 0 com.samsung.android.aware.service
pm disable --user 0 com.sec.android.app.fm
pm disable --user 0 com.sec.app.RilErrorNotifier
pm disable --user 0 com.sec.android.app.safetyassurance
pm disable --user 0 com.samsung.safetyinformation
pm disable --user 0 com.osp.app.signin
pm disable --user 0 com.sec.android.app.billing
pm disable --user 0 com.samsung.android.scloud
pm disable --user 0 com.samsung.android.app.spage
pm disable --user 0 com.samsung.android.mobileservice
pm disable --user 0 com.samsung.android.mateagent
pm disable --user 0 com.samsung.android.kidsinstaller
pm disable --user 0 com.sec.location.nsflp2
pm disable --user 0 com.samsung.android.authfw
pm disable --user 0 com.samsung.android.samsungpass
pm disable --user 0 com.samsung.android.spayfw
pm disable --user 0 com.sec.spp.push
pm disable --user 0 com.sec.android.app.SecSetupWizard
pm disable --user 0 com.samsung.SMT
pm disable --user 0 com.samsung.android.sm.policy
pm disable --user 0 com.samsung.knox.securefolder
pm disable --user 0 com.android.se
pm disable --user 0 com.samsung.android.securitylogagent
pm disable --user 0 com.sec.sve
pm disable --user 0 com.sec.android.app.ve.vebgm
pm disable --user 0 com.sec.android.app.servicemodeapp
pm disable --user 0 com.sec.android.RilServiceModeApp
pm disable --user 0 com.sec.location.nfwlocationprivacy
pm disable --user 0 com.samsung.android.app.settings.bixby
pm disable --user 0 com.sec.android.app.setupwizardlegalprovider
pm disable --user 0 com.samsung.ims.smk
pm disable --user 0 com.skms.android.agent
pm disable --user 0 com.samsung.android.location
pm disable --user 0 com.samsung.android.smartcallprovider
pm disable --user 0 com.sec.android.easyMover.Agent
pm disable --user 0 com.samsung.android.smartmirroring
pm disable --user 0 com.samsung.android.smartface
pm disable --user 0 com.samsung.android.beaconmanager
pm disable --user 0 com.sec.android.soagent
pm disable --user 0 com.sec.android.app.soundalive
pm disable --user 0 com.samsung.android.stickercenter
pm disable --user 0 com.samsung.android.svcagent
pm disable --user 0 com.samsung.android.tadownloader
pm disable --user 0 com.trustonic.teeservice
pm disable --user 0 com.sec.automation
pm disable --user 0 com.samsung.android.uds
pm disable --user 0 com.sec.android.widgetapp.webmanual
pm disable --user 0 com.samsung.android.dynamiclock
pm disable --user 0 com.samsung.android.app.watchmanagerstub
pm disable --user 0 com.sec.android.daemonapp
pm disable --user 0 com.sec.unifiedwfc
pm disable --user 0 com.samsung.android.allshare.service.fileshare
pm disable --user 0 com.samsung.android.net.wifi.wifiguider
pm disable --user 0 com.sec.android.app.wlantest
pm disable --user 0 com.samsung.android.knox.containeragent
pm disable --user 0 com.microsoft.appmanager
